from yacs.config import CfgNode as CN

MODELS = CN()

MODELS.IMAGE_BACKBONE_WEIGHTS = ""

MODELS.NAME = "HRNet48v2"
MODELS.DEVICE = "cuda"
MODELS.HEAD_SIZE  = [[2]]
MODELS.OUT_FEATURE_CHANNELS = 256

MODELS.LOSS_WEIGHTS = CN(new_allowed=True)

POINT_ENCODER = CN()
MODELS.POINT_ENCODER = POINT_ENCODER
MODELS.POINT_ENCODER.voxel_size = 4
MODELS.POINT_ENCODER.max_voxels = 16000
MODELS.POINT_ENCODER.max_num_points = 16

MODELS.USE_IMAGES = 1
MODELS.USE_LIDAR = 1